name: Firebase Deploy

on:
  push:
    branches:
      - main  # Set to the branch that triggers deployment (e.g., main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure the version matches your project needs

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build your project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
